<script>
export const tasks = [
  {
    id: "tsk_001",
    title: "Design dashboard wireframe",
    description: "Create low-fidelity wireframes for the admin dashboard.",
    status: "in-progress",
    priority: "high",
    assignee: "Chidera Okonkwo",
    tags: ["design", "ui", "dashboard"],
    dueDate: "2026-03-01",
    createdAt: "2026-02-20T09:15:00Z",
    completed: false,
    progress: 45
  },
  {
    id: "tsk_002",
    title: "Implement authentication flow",
    description: "Set up Firebase email and Google authentication.",
    status: "todo",
    priority: "high",
    assignee: "Chidera Okonkwo",
    tags: ["firebase", "auth", "backend"],
    dueDate: "2026-03-05",
    createdAt: "2026-02-21T11:00:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_003",
    title: "Fix mobile navbar bug",
    description: "Resolve overflow issue on small screens.",
    status: "in-progress",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["bug", "responsive", "css"],
    dueDate: "2026-02-28",
    createdAt: "2026-02-19T14:32:00Z",
    completed: false,
    progress: 70
  },
  {
    id: "tsk_004",
    title: "Write unit tests for utils",
    description: "Increase coverage for helper functions.",
    status: "blocked",
    priority: "medium",
    assignee: "QA Team",
    tags: ["testing", "jest"],
    dueDate: "2026-03-10",
    createdAt: "2026-02-18T08:10:00Z",
    completed: false,
    progress: 20
  },
  {
    id: "tsk_005",
    title: "Deploy latest build to Vercel",
    description: "Push production build and verify environment variables.",
    status: "completed",
    priority: "low",
    assignee: "DevOps",
    tags: ["deployment", "vercel"],
    dueDate: "2026-02-22",
    createdAt: "2026-02-17T16:45:00Z",
    completed: true,
    progress: 100
  },
  {
    id: "tsk_006",
    title: "Add dark mode toggle",
    description: "Implement theme switch using Context API.",
    status: "todo",
    priority: "medium",
    assignee: "Chidera Okonkwo",
    tags: ["feature", "theme", "react"],
    dueDate: "2026-03-07",
    createdAt: "2026-02-24T10:05:00Z",
    completed: false,
    progress: 0
  },

  // 🔥 MORE TASKS

  {
    id: "tsk_007",
    title: "Optimize image loading",
    description: "Implement lazy loading for dashboard images.",
    status: "in-progress",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["performance", "images"],
    dueDate: "2026-03-04",
    createdAt: "2026-02-23T09:40:00Z",
    completed: false,
    progress: 55
  },
  {
    id: "tsk_008",
    title: "Create reusable modal component",
    description: "Build a flexible modal using Headless UI.",
    status: "todo",
    priority: "medium",
    assignee: "Chidera Okonkwo",
    tags: ["component", "react", "ui"],
    dueDate: "2026-03-09",
    createdAt: "2026-02-24T13:22:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_009",
    title: "Fix form validation edge cases",
    description: "Handle empty and malformed inputs.",
    status: "blocked",
    priority: "high",
    assignee: "QA Team",
    tags: ["forms", "validation", "bug"],
    dueDate: "2026-03-02",
    createdAt: "2026-02-22T15:11:00Z",
    completed: false,
    progress: 25
  },
  {
    id: "tsk_010",
    title: "Add skeleton loaders",
    description: "Improve perceived loading performance.",
    status: "in-progress",
    priority: "low",
    assignee: "Frontend Team",
    tags: ["ux", "loading", "react"],
    dueDate: "2026-03-06",
    createdAt: "2026-02-23T18:05:00Z",
    completed: false,
    progress: 60
  },
  {
    id: "tsk_011",
    title: "Set up error boundary",
    description: "Catch and display React runtime errors gracefully.",
    status: "todo",
    priority: "high",
    assignee: "Chidera Okonkwo",
    tags: ["react", "stability"],
    dueDate: "2026-03-08",
    createdAt: "2026-02-24T19:30:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_012",
    title: "Refactor sidebar navigation",
    description: "Improve accessibility and keyboard navigation.",
    status: "completed",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["a11y", "navigation"],
    dueDate: "2026-02-21",
    createdAt: "2026-02-16T12:00:00Z",
    completed: true,
    progress: 100
  },
  {
    id: "tsk_013",
    title: "Implement role-based guards",
    description: "Protect admin and writer routes.",
    status: "in-progress",
    priority: "high",
    assignee: "Chidera Okonkwo",
    tags: ["auth", "security", "react"],
    dueDate: "2026-03-11",
    createdAt: "2026-02-25T08:55:00Z",
    completed: false,
    progress: 40
  },
  {
    id: "tsk_014",
    title: "Improve Lighthouse score",
    description: "Target performance score above 90.",
    status: "todo",
    priority: "low",
    assignee: "DevOps",
    tags: ["performance", "audit"],
    dueDate: "2026-03-15",
    createdAt: "2026-02-25T09:20:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_015",
    title: "Add toast notification system",
    description: "Global success and error feedback.",
    status: "in-progress",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["ux", "notifications"],
    dueDate: "2026-03-03",
    createdAt: "2026-02-23T07:10:00Z",
    completed: false,
    progress: 65
  },
  {
    id: "tsk_016",
    title: "Create onboarding checklist page",
    description: "Guide new users through first-time setup steps.",
    status: "todo",
    priority: "medium",
    assignee: "Product Team",
    tags: ["onboarding", "ux", "frontend"],
    dueDate: "2026-03-12",
    createdAt: "2026-02-25T11:15:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_017",
    title: "Integrate analytics events",
    description: "Track key actions for signup and task completion.",
    status: "in-progress",
    priority: "high",
    assignee: "Chidera Okonkwo",
    tags: ["analytics", "tracking", "events"],
    dueDate: "2026-03-06",
    createdAt: "2026-02-25T11:35:00Z",
    completed: false,
    progress: 35
  },
  {
    id: "tsk_018",
    title: "Add pagination to activity list",
    description: "Load activity items in chunks for better performance.",
    status: "todo",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["pagination", "performance", "ui"],
    dueDate: "2026-03-14",
    createdAt: "2026-02-25T12:00:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_019",
    title: "Harden API error handling",
    description: "Normalize API errors and surface actionable messages.",
    status: "in-progress",
    priority: "high",
    assignee: "Backend Team",
    tags: ["api", "errors", "reliability"],
    dueDate: "2026-03-05",
    createdAt: "2026-02-25T12:20:00Z",
    completed: false,
    progress: 50
  },
  {
    id: "tsk_020",
    title: "Implement CSV export for reports",
    description: "Allow users to export filtered data tables as CSV.",
    status: "todo",
    priority: "low",
    assignee: "Data Team",
    tags: ["reports", "export", "csv"],
    dueDate: "2026-03-18",
    createdAt: "2026-02-25T12:45:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_021",
    title: "Improve keyboard shortcuts",
    description: "Add shortcut support for quick task management.",
    status: "in-progress",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["accessibility", "keyboard", "productivity"],
    dueDate: "2026-03-09",
    createdAt: "2026-02-25T13:05:00Z",
    completed: false,
    progress: 30
  },
  {
    id: "tsk_022",
    title: "Set up nightly backup jobs",
    description: "Automate secure backups for production database.",
    status: "blocked",
    priority: "high",
    assignee: "DevOps",
    tags: ["backup", "infrastructure", "security"],
    dueDate: "2026-03-07",
    createdAt: "2026-02-25T13:25:00Z",
    completed: false,
    progress: 10
  },
  {
    id: "tsk_023",
    title: "Add profile photo upload",
    description: "Support image upload, crop, and preview in settings.",
    status: "todo",
    priority: "medium",
    assignee: "Chidera Okonkwo",
    tags: ["profile", "upload", "media"],
    dueDate: "2026-03-16",
    createdAt: "2026-02-25T13:40:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_024",
    title: "Document component library usage",
    description: "Write examples and dos/don'ts for shared components.",
    status: "completed",
    priority: "low",
    assignee: "Docs Team",
    tags: ["documentation", "components"],
    dueDate: "2026-02-26",
    createdAt: "2026-02-25T13:55:00Z",
    completed: true,
    progress: 100
  },
  
  {
    id: "tsk_026",
    title: "Create empty state illustrations",
    description: "Design and integrate empty state visuals for key pages.",
    status: "todo",
    priority: "low",
    assignee: "Design Team",
    tags: ["design", "illustration", "ui"],
    dueDate: "2026-03-19",
    createdAt: "2026-02-25T14:20:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_027",
    title: "Audit bundle size",
    description: "Identify large dependencies and reduce JS payload.",
    status: "in-progress",
    priority: "high",
    assignee: "Frontend Team",
    tags: ["performance", "bundle", "vite"],
    dueDate: "2026-03-08",
    createdAt: "2026-02-25T14:30:00Z",
    completed: false,
    progress: 40
  },
  {
    id: "tsk_028",
    title: "Implement forgot password flow",
    description: "Add reset link request and confirmation screens.",
    status: "todo",
    priority: "high",
    assignee: "Chidera Okonkwo",
    tags: ["auth", "security", "ux"],
    dueDate: "2026-03-10",
    createdAt: "2026-02-25T14:40:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_029",
    title: "Set up staging environment",
    description: "Mirror production config for QA validation.",
    status: "blocked",
    priority: "high",
    assignee: "DevOps",
    tags: ["staging", "infrastructure", "deploy"],
    dueDate: "2026-03-09",
    createdAt: "2026-02-25T14:50:00Z",
    completed: false,
    progress: 15
  },
  {
    id: "tsk_030",
    title: "Add table column resizing",
    description: "Enable drag-to-resize for report table columns.",
    status: "in-progress",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["table", "interaction", "ui"],
    dueDate: "2026-03-13",
    createdAt: "2026-02-25T15:00:00Z",
    completed: false,
    progress: 35
  },
  {
    id: "tsk_031",
    title: "Review API rate limits",
    description: "Document current limits and fallback behavior.",
    status: "todo",
    priority: "medium",
    assignee: "Backend Team",
    tags: ["api", "limits", "documentation"],
    dueDate: "2026-03-15",
    createdAt: "2026-02-25T15:10:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_032",
    title: "Build account settings page",
    description: "Create profile, password, and notification sections.",
    status: "in-progress",
    priority: "medium",
    assignee: "Chidera Okonkwo",
    tags: ["settings", "profile", "frontend"],
    dueDate: "2026-03-12",
    createdAt: "2026-02-25T15:20:00Z",
    completed: false,
    progress: 45
  },
  {
    id: "tsk_033",
    title: "Add route loading indicators",
    description: "Show progress while navigating between pages.",
    status: "todo",
    priority: "low",
    assignee: "Frontend Team",
    tags: ["routing", "loading", "ux"],
    dueDate: "2026-03-18",
    createdAt: "2026-02-25T15:30:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_034",
    title: "Create API mock fixtures",
    description: "Prepare consistent mock payloads for UI testing.",
    status: "completed",
    priority: "medium",
    assignee: "QA Team",
    tags: ["testing", "mocks", "api"],
    dueDate: "2026-02-27",
    createdAt: "2026-02-25T15:40:00Z",
    completed: true,
    progress: 100
  },
  {
    id: "tsk_035",
    title: "Implement notification preferences",
    description: "Allow users to toggle email and in-app alerts.",
    status: "todo",
    priority: "medium",
    assignee: "Product Team",
    tags: ["notifications", "preferences", "settings"],
    dueDate: "2026-03-17",
    createdAt: "2026-02-25T15:50:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_036",
    title: "Fix date picker timezone issue",
    description: "Ensure selected dates remain stable across locales.",
    status: "in-progress",
    priority: "high",
    assignee: "Frontend Team",
    tags: ["bug", "timezone", "date"],
    dueDate: "2026-03-06",
    createdAt: "2026-02-25T16:00:00Z",
    completed: false,
    progress: 60
  },
  {
    id: "tsk_037",
    title: "Set up audit logs",
    description: "Track sensitive admin actions for compliance.",
    status: "todo",
    priority: "high",
    assignee: "Backend Team",
    tags: ["security", "compliance", "logging"],
    dueDate: "2026-03-11",
    createdAt: "2026-02-25T16:10:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_038",
    title: "Refine empty search results UI",
    description: "Improve messaging and quick actions for no results.",
    status: "in-progress",
    priority: "low",
    assignee: "Design Team",
    tags: ["search", "ux", "copy"],
    dueDate: "2026-03-14",
    createdAt: "2026-02-25T16:20:00Z",
    completed: false,
    progress: 50
  },
  {
    id: "tsk_039",
    title: "Add keyboard focus outlines",
    description: "Improve visibility of focus states for accessibility.",
    status: "completed",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["a11y", "keyboard", "css"],
    dueDate: "2026-02-28",
    createdAt: "2026-02-25T16:30:00Z",
    completed: true,
    progress: 100
  },
  {
    id: "tsk_040",
    title: "Implement search debouncing",
    description: "Reduce unnecessary API calls while typing.",
    status: "in-progress",
    priority: "medium",
    assignee: "Chidera Okonkwo",
    tags: ["search", "performance", "api"],
    dueDate: "2026-03-07",
    createdAt: "2026-02-25T16:40:00Z",
    completed: false,
    progress: 55
  },
  {
    id: "tsk_041",
    title: "Create release notes template",
    description: "Standardize release communication format.",
    status: "todo",
    priority: "low",
    assignee: "Product Team",
    tags: ["release", "docs", "process"],
    dueDate: "2026-03-20",
    createdAt: "2026-02-25T16:50:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_042",
    title: "Secure file upload endpoints",
    description: "Validate MIME types and enforce upload limits.",
    status: "blocked",
    priority: "high",
    assignee: "Backend Team",
    tags: ["security", "upload", "api"],
    dueDate: "2026-03-10",
    createdAt: "2026-02-25T17:00:00Z",
    completed: false,
    progress: 20
  },
  {
    id: "tsk_043",
    title: "Add drag-and-drop task sorting",
    description: "Allow users to reorder tasks in the list.",
    status: "todo",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["dnd", "tasks", "interaction"],
    dueDate: "2026-03-16",
    createdAt: "2026-02-25T17:10:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_044",
    title: "Implement optimistic UI updates",
    description: "Reflect changes instantly before server confirmation.",
    status: "in-progress",
    priority: "high",
    assignee: "Chidera Okonkwo",
    tags: ["ux", "state", "api"],
    dueDate: "2026-03-08",
    createdAt: "2026-02-25T17:20:00Z",
    completed: false,
    progress: 42
  },
  {
    id: "tsk_045",
    title: "Define component naming conventions",
    description: "Create guidelines for reusable UI components.",
    status: "completed",
    priority: "low",
    assignee: "Frontend Team",
    tags: ["standards", "components", "docs"],
    dueDate: "2026-02-27",
    createdAt: "2026-02-25T17:30:00Z",
    completed: true,
    progress: 100
  },
  {
    id: "tsk_046",
    title: "Migrate legacy utility classes",
    description: "Replace deprecated classes with current Tailwind utilities.",
    status: "in-progress",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["tailwind", "refactor", "css"],
    dueDate: "2026-03-13",
    createdAt: "2026-02-25T17:40:00Z",
    completed: false,
    progress: 58
  },
  {
    id: "tsk_047",
    title: "Add user activity timeline",
    description: "Display chronological activity entries on profile pages.",
    status: "todo",
    priority: "medium",
    assignee: "Product Team",
    tags: ["timeline", "profile", "feature"],
    dueDate: "2026-03-18",
    createdAt: "2026-02-25T17:50:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_048",
    title: "Implement SSO integration spike",
    description: "Research and prototype enterprise sign-on approach.",
    status: "in-progress",
    priority: "high",
    assignee: "Backend Team",
    tags: ["sso", "auth", "research"],
    dueDate: "2026-03-12",
    createdAt: "2026-02-25T18:00:00Z",
    completed: false,
    progress: 33
  },
  {
    id: "tsk_049",
    title: "Improve offline fallback messaging",
    description: "Show actionable guidance when connection is lost.",
    status: "todo",
    priority: "low",
    assignee: "Frontend Team",
    tags: ["offline", "ux", "resilience"],
    dueDate: "2026-03-21",
    createdAt: "2026-02-25T18:10:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_050",
    title: "Create QA smoke test checklist",
    description: "Document must-pass checks before each release.",
    status: "completed",
    priority: "medium",
    assignee: "QA Team",
    tags: ["qa", "testing", "release"],
    dueDate: "2026-02-28",
    createdAt: "2026-02-25T18:20:00Z",
    completed: true,
    progress: 100
  },
  {
    id: "tsk_051",
    title: "Optimize API caching headers",
    description: "Tune cache-control for static and semi-static endpoints.",
    status: "in-progress",
    priority: "medium",
    assignee: "Backend Team",
    tags: ["api", "cache", "performance"],
    dueDate: "2026-03-09",
    createdAt: "2026-02-25T18:30:00Z",
    completed: false,
    progress: 48
  },
  {
    id: "tsk_052",
    title: "Add success metrics dashboard",
    description: "Track adoption and completion KPIs in one view.",
    status: "todo",
    priority: "low",
    assignee: "Data Team",
    tags: ["metrics", "dashboard", "analytics"],
    dueDate: "2026-03-22",
    createdAt: "2026-02-25T18:40:00Z",
    completed: false,
    progress: 0
  },
  {
    id: "tsk_053",
    title: "Improve form error summaries",
    description: "Add top-level error summary with anchor links.",
    status: "in-progress",
    priority: "medium",
    assignee: "Frontend Team",
    tags: ["forms", "a11y", "ux"],
    dueDate: "2026-03-11",
    createdAt: "2026-02-25T18:50:00Z",
    completed: false,
    progress: 52
  },
  {
    id: "tsk_054",
    title: "Set up dependency update policy",
    description: "Define monthly update cadence and ownership.",
    status: "todo",
    priority: "low",
    assignee: "DevOps",
    tags: ["dependencies", "maintenance", "process"],
    dueDate: "2026-03-23",
    createdAt: "2026-02-25T19:00:00Z",
    completed: false,
    progress: 0
  }
 
];</script>


